In [2]:
!pip install python-binance

Requirement already satisfied: python-binance in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (1.0.16)
Requirement already satisfied: aiohttp in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-binance) (3.7.4.post0)
Requirement already satisfied: dateparser in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-binance) (1.1.1)
Requirement already satisfied: six in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-binance) (1.16.0)
Requirement already satisfied: websockets in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-binance) (10.3)
Requirement already satisfied: ujson in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-binance) (5.5.0)
Requirement already satisfied: requests in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-binance) (2.26.0)
Requirement already satisfied: chardet<5.0,>=2.0 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp->python-binance) (4.0.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp->python-binance) (21.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp->python-binance) (5.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp->python-binance) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp->python-binance) (3.10.0.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from aiohttp->python-binance) (3.0.1)
Requirement already satisfied: pytz in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from dateparser->python-binance) (2021.3)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27,<2022.3.15 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from dateparser->python-binance) (2022.3.2)
Requirement already satisfied: tzlocal in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from dateparser->python-binance) (4.2)
Requirement already satisfied: python-dateutil in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from dateparser->python-binance) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests->python-binance) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests->python-binance) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests->python-binance) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests->python-binance) (2.0.7)
Requirement already satisfied: pytz-deprecation-shim in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from tzlocal->dateparser->python-binance) (0.1.0.post0)
Requirement already satisfied: tzdata in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from tzlocal->dateparser->python-binance) (2022.1)

WARNING: There was an error checking the latest version of pip.

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (1.3.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (1.21.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

WARNING: There was an error checking the latest version of pip.

In [4]:
!pip install bs4

Requirement already satisfied: bs4 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\theom\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from beautifulsoup4->bs4) (2.3.1)

WARNING: There was an error checking the latest version of pip.

In [5]:
from binance import Client
import pandas as pd

In [19]:
def rsi(df, periods = 14, ema = True):
    """
    Returns a pd.Series with the relative strength index.
    """
    close_delta = df['open'].diff()
    # Make two series: one for lower closes and one for higher closes
    up = close_delta.clip(lower=0)
    down = -1 * close_delta.clip(upper=0)
    
    if ema == True:
        # Use exponential moving average
        ma_up = up.ewm(com = periods - 1, adjust=True, min_periods = periods).mean()
        ma_down = down.ewm(com = periods - 1, adjust=True, min_periods = periods).mean()
    else:
        # Use simple moving average
        ma_up = up.rolling(window = periods, adjust=False).mean()
        ma_down = down.rolling(window = periods, adjust=False).mean()
        
    rsi = ma_up / ma_down
    rsi = 100 - (100/(1 + rsi))
    return rsi

In [ ]:
#----------------------------------- CODE FONCTIONNEL --------------------------------------------

In [6]:
client = Client()

PAIRNAME = ['1INCHUSDT','AAVEUSDT','ACAUSDT','ACHUSDT','ACMUSDT','ADAUSDT','ADXUSDT','AGLDUSDT','ADXUSDT','AIONUSDT','AKROUSDT','ALCXUSDT','ALGOUSDT','ALICEUSDT','ALPACAUSDT','ALPINEUSDT','AMPUSDT','ANCUSDT','ANKRUSDT','ANTUSDT','APEUSDT','API3USDT','ARDRUSDT','ARPAUSDT','ARUSDT','ASRUSDT','ASTRUSDT','ATMUSDT','ATOMUSDT','AUCTIONUSDT','AUDIOUSDT','AUDUSDT','AUTOUSDT','AVAUSDT','AVAXUSDT','AXSUSDT','BADGERUSDT','BAKEUSDT','BALUSDT','BANDUSDT','BARUSDT','BATUSDT','BCHUSDT','BEAMUSDT','BELUSDT','BETAUSDT','BICOUSDT','BIFIUSDT','BLZUSDT','BNBUSDT','BNTUSDT','BNXUSDT','BONDUSDT','BSWUSDT','BTCSTUSDT','BTCUSDT','BTGUSDT','BTSUSDT','BTTCUSDT','BURGERUSDT','BUSDUSDT','C98USDT','CAKEUSDT','CELOUSDT','CELRUSDT','CFXUSDT','CHESSUSDT','CHRUSDT','CHZUSDT','CITYUSDT','CKBUSDT','CLVUSDT','COCOSUSDT','COMPUSDT','COSUSDT','COTIUSDT','CRVUSDT','CTKUSDT','CTSIUSDT','CTXCUSDT','CVCUSDT','CVPUSDT','CVXUSDT','DARUSDT','DASHUSDT','DATAUSDT','DCRUSDT','DEGOUSDT','DENTUSDT','DEXEUSDT','DFUSDT','DGBUSDT','DIAUSDT','DNTUSDT','DOCKUSDT','DODOUSDT','DOGEUSDT','DOTUSDT','DREPUSDT','DUSKUSDT','DYDXUSDT','EGLDUSDT','ELFUSDT','ENJUSDT','ENSUSDT','EOSUSDT','EPXUSDT','ERNUSDT','ETCUSDT','ETHUSDT','FARMUSDT','FETUSDT','FIDAUSDT','FILUSDT','FIOUSDT','FIROUSDT','FISUSDT','FLMUSDT','FLOWUSDT','FLUXUSDT','FORTHUSDT','FORUSDT','FRONTUSDT','FTMUSDT','FTTUSDT','FUNUSDT','FXSUSDT']
# List of pairs of crypto
startDate = "01 january 2017"
timeInterval = Client.KLINE_INTERVAL_1DAY
# Interval = 1DAY

klines = client.get_historical_klines('BTCUSDT', timeInterval, startDate)
# We ask binance API to get all the data from 'BTCUSDT' from start date to today with our time interval, we chose BTCUSDCT because its one of the oldest one so we have all the date 
Database_Price_Open = pd.DataFrame(klines,columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])
Database_Price_Open = Database_Price_Open.set_index(['timestamp'])
Database_Price_Open.index = pd.to_datetime(Database_Price_Open.index, unit='ms')
Database_Price_Open = Database_Price_Open.drop(columns = ['open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])

# We drop info, and use dataframe so we get all the dates
Database_Price_Open

Empty DataFrame
Columns: []
Index: [2017-08-17 00:00:00, 2017-08-18 00:00:00, 2017-08-19 00:00:00, 2017-08-20 00:00:00, 2017-08-21 00:00:00, 2017-08-22 00:00:00, 2017-08-23 00:00:00, 2017-08-24 00:00:00, 2017-08-25 00:00:00, 2017-08-26 00:00:00, 2017-08-27 00:00:00, 2017-08-28 00:00:00, 2017-08-29 00:00:00, 2017-08-30 00:00:00, 2017-08-31 00:00:00, 2017-09-01 00:00:00, 2017-09-02 00:00:00, 2017-09-03 00:00:00, 2017-09-04 00:00:00, 2017-09-05 00:00:00, 2017-09-06 00:00:00, 2017-09-07 00:00:00, 2017-09-08 00:00:00, 2017-09-09 00:00:00, 2017-09-10 00:00:00, 2017-09-11 00:00:00, 2017-09-12 00:00:00, 2017-09-13 00:00:00, 2017-09-14 00:00:00, 2017-09-15 00:00:00, 2017-09-16 00:00:00, 2017-09-17 00:00:00, 2017-09-18 00:00:00, 2017-09-19 00:00:00, 2017-09-20 00:00:00, 2017-09-21 00:00:00, 2017-09-22 00:00:00, 2017-09-23 00:00:00, 2017-09-24 00:00:00, 2017-09-25 00:00:00, 2017-09-26 00:00:00, 2017-09-27 00:00:00, 2017-09-28 00:00:00, 2017-09-29 00:00:00, 2017-09-30 00:00:00, 2017-10-01 00:00:00, 2017-10-02 00:00:00, 2017-10-03 00:00:00, 2017-10-04 00:00:00, 2017-10-05 00:00:00, 2017-10-06 00:00:00, 2017-10-07 00:00:00, 2017-10-08 00:00:00, 2017-10-09 00:00:00, 2017-10-10 00:00:00, 2017-10-11 00:00:00, 2017-10-12 00:00:00, 2017-10-13 00:00:00, 2017-10-14 00:00:00, 2017-10-15 00:00:00, 2017-10-16 00:00:00, 2017-10-17 00:00:00, 2017-10-18 00:00:00, 2017-10-19 00:00:00, 2017-10-20 00:00:00, 2017-10-21 00:00:00, 2017-10-22 00:00:00, 2017-10-23 00:00:00, 2017-10-24 00:00:00, 2017-10-25 00:00:00, 2017-10-26 00:00:00, 2017-10-27 00:00:00, 2017-10-28 00:00:00, 2017-10-29 00:00:00, 2017-10-30 00:00:00, 2017-10-31 00:00:00, 2017-11-01 00:00:00, 2017-11-02 00:00:00, 2017-11-03 00:00:00, 2017-11-04 00:00:00, 2017-11-05 00:00:00, 2017-11-06 00:00:00, 2017-11-07 00:00:00, 2017-11-08 00:00:00, 2017-11-09 00:00:00, 2017-11-10 00:00:00, 2017-11-11 00:00:00, 2017-11-12 00:00:00, 2017-11-13 00:00:00, 2017-11-14 00:00:00, 2017-11-15 00:00:00, 2017-11-16 00:00:00, 2017-11-17 00:00:00, 2017-11-18 00:00:00, 2017-11-19 00:00:00, 2017-11-20 00:00:00, 2017-11-21 00:00:00, 2017-11-22 00:00:00, 2017-11-23 00:00:00, 2017-11-24 00:00:00, ...]

[1894 rows x 0 columns]

In [7]:
for pair in PAIRNAME:
    # For each crypto pairs we ask binance API for info
    klinesT = client.get_historical_klines(pair, timeInterval, startDate)
    df = pd.DataFrame(klinesT, columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])
    df['open'] = pd.to_numeric(df['open'])
    df = df.set_index(df['timestamp'])
    df.index = pd.to_datetime(df.index, unit='ms')
    Database_Price_Open[f'{pair}'] = df['open']
    # For each open price of the pairs we add it to our database, NaN means the pairs was not tradeable on Binance
    del df
    # df is a temporary dataframe, we delete it for each iteration so we don't waste memory

Database_Price_Open

C:\Users\theom\AppData\Local\Temp\ipykernel_20076\1812120610.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  Database_Price_Open[f'{pair}'] = df['open']

,1INCHUSDT,AAVEUSDT,ACAUSDT,ACHUSDT,ACMUSDT,ADAUSDT,ADXUSDT,AGLDUSDT,AIONUSDT,AKROUSDT,...,FLMUSDT,FLOWUSDT,FLUXUSDT,FORTHUSDT,FORUSDT,FRONTUSDT,FTMUSDT,FTTUSDT,FUNUSDT,FXSUSDT
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-08-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-19,0.570,82.4,0.1661,0.01188,3.169,0.3624,0.1561,0.311,0.04568,0.00354,...,0.1089,1.526,0.754,4.15,0.01862,0.2293,0.2086,23.58,0.00727,6.699
2022-10-20,0.566,82.8,0.1644,0.01143,3.042,0.3496,0.1548,0.304,0.03962,0.00336,...,0.1039,1.445,0.704,4.07,0.01849,0.2250,0.1988,22.58,0.00721,6.090
2022-10-21,0.562,80.8,0.1615,0.01135,2.965,0.3402,0.1578,0.307,0.03858,0.00339,...,0.1023,1.429,0.696,3.96,0.01825,0.2239,0.1994,22.42,0.00718,6.131
2022-10-22,0.569,82.1,0.1614,0.01190,3.045,0.3492,0.1585,0.310,0.03784,0.00343,...,0.1032,1.449,0.691,4.01,0.01807,0.2244,0.2050,22.45,0.00724,6.181
2022-10-23,0.571,82.1,0.1648,0.01109,3.013,0.3513,0.1757,0.309,0.03803,0.00352,...,0.1044,1.469,0.684,4.01,0.02051,0.2343,0.2044,22.59,0.00724,5.996

In [28]:
klines = client.get_historical_klines('BTCUSDT', timeInterval, startDate)
Database_RSI = pd.DataFrame(klines,columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])
Database_RSI = Database_RSI.set_index(['timestamp'])
Database_RSI.index = pd.to_datetime(Database_RSI.index, unit='ms')
Database_RSI = Database_RSI.drop(columns = ['open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])

#Database_RSI

Empty DataFrame
Columns: []
Index: [2017-08-17 00:00:00, 2017-08-18 00:00:00, 2017-08-19 00:00:00, 2017-08-20 00:00:00, 2017-08-21 00:00:00, 2017-08-22 00:00:00, 2017-08-23 00:00:00, 2017-08-24 00:00:00, 2017-08-25 00:00:00, 2017-08-26 00:00:00, 2017-08-27 00:00:00, 2017-08-28 00:00:00, 2017-08-29 00:00:00, 2017-08-30 00:00:00, 2017-08-31 00:00:00, 2017-09-01 00:00:00, 2017-09-02 00:00:00, 2017-09-03 00:00:00, 2017-09-04 00:00:00, 2017-09-05 00:00:00, 2017-09-06 00:00:00, 2017-09-07 00:00:00, 2017-09-08 00:00:00, 2017-09-09 00:00:00, 2017-09-10 00:00:00, 2017-09-11 00:00:00, 2017-09-12 00:00:00, 2017-09-13 00:00:00, 2017-09-14 00:00:00, 2017-09-15 00:00:00, 2017-09-16 00:00:00, 2017-09-17 00:00:00, 2017-09-18 00:00:00, 2017-09-19 00:00:00, 2017-09-20 00:00:00, 2017-09-21 00:00:00, 2017-09-22 00:00:00, 2017-09-23 00:00:00, 2017-09-24 00:00:00, 2017-09-25 00:00:00, 2017-09-26 00:00:00, 2017-09-27 00:00:00, 2017-09-28 00:00:00, 2017-09-29 00:00:00, 2017-09-30 00:00:00, 2017-10-01 00:00:00, 2017-10-02 00:00:00, 2017-10-03 00:00:00, 2017-10-04 00:00:00, 2017-10-05 00:00:00, 2017-10-06 00:00:00, 2017-10-07 00:00:00, 2017-10-08 00:00:00, 2017-10-09 00:00:00, 2017-10-10 00:00:00, 2017-10-11 00:00:00, 2017-10-12 00:00:00, 2017-10-13 00:00:00, 2017-10-14 00:00:00, 2017-10-15 00:00:00, 2017-10-16 00:00:00, 2017-10-17 00:00:00, 2017-10-18 00:00:00, 2017-10-19 00:00:00, 2017-10-20 00:00:00, 2017-10-21 00:00:00, 2017-10-22 00:00:00, 2017-10-23 00:00:00, 2017-10-24 00:00:00, 2017-10-25 00:00:00, 2017-10-26 00:00:00, 2017-10-27 00:00:00, 2017-10-28 00:00:00, 2017-10-29 00:00:00, 2017-10-30 00:00:00, 2017-10-31 00:00:00, 2017-11-01 00:00:00, 2017-11-02 00:00:00, 2017-11-03 00:00:00, 2017-11-04 00:00:00, 2017-11-05 00:00:00, 2017-11-06 00:00:00, 2017-11-07 00:00:00, 2017-11-08 00:00:00, 2017-11-09 00:00:00, 2017-11-10 00:00:00, 2017-11-11 00:00:00, 2017-11-12 00:00:00, 2017-11-13 00:00:00, 2017-11-14 00:00:00, 2017-11-15 00:00:00, 2017-11-16 00:00:00, 2017-11-17 00:00:00, 2017-11-18 00:00:00, 2017-11-19 00:00:00, 2017-11-20 00:00:00, 2017-11-21 00:00:00, 2017-11-22 00:00:00, 2017-11-23 00:00:00, 2017-11-24 00:00:00, ...]

[1888 rows x 0 columns]

In [30]:
for pair in PAIRNAME:
    klinesT = client.get_historical_klines(pair, timeInterval, startDate)
    df = pd.DataFrame(klinesT, columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])
    df['open'] = pd.to_numeric(df['open'])
    df = df.set_index(df['timestamp'])
    df.index = pd.to_datetime(df.index, unit='ms')
    Database_RSI[f'{pair}'] = Database_RSI.apply(lambda _: '', axis=1)
    df = df.drop(columns = ['timestamp','high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])
    Database_RSI[f'{pair}'] = rsi(df)
    del df

Database_RSI

,1INCHUSDT,AAVEUSDT,ACAUSDT,ACHUSDT,ACMUSDT,ADAUSDT,ADXUSDT,AGLDUSDT,AIONUSDT,AKROUSDT,...,FLMUSDT,FLOWUSDT,FLUXUSDT,FORTHUSDT,FORUSDT,FRONTUSDT,FTMUSDT,FTTUSDT,FUNUSDT,FXSUSDT
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-08-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-13,43.610483,38.693456,29.648271,32.303899,29.243029,27.336693,37.690221,41.817914,26.923090,38.228818,...,40.473618,35.494036,31.726413,32.791549,40.754172,48.967884,32.883418,39.378843,39.148055,47.725024
2022-10-14,42.251670,37.890237,29.292484,31.154884,28.388516,26.289939,33.520303,38.976444,25.063310,36.075674,...,39.154976,32.554975,30.062338,27.694957,37.978811,45.483859,31.853128,40.331011,42.364648,50.312966
2022-10-15,42.050101,42.753356,27.809968,68.388915,27.738908,24.042676,35.752967,38.573214,24.739990,38.857141,...,38.125972,30.746560,39.532659,27.439798,37.780898,49.169926,30.173266,40.456908,43.959707,59.569155
2022-10-16,42.050101,40.763375,40.245282,52.293347,27.738908,23.491448,42.041607,39.912127,36.540051,53.959126,...,39.662860,29.994100,41.760312,30.209612,44.802363,50.922992,30.173266,39.037669,38.258459,71.259110
2022-10-17,44.506398,50.088510,42.120037,53.910807,33.119150,27.745631,51.732872,49.906963,77.760536,45.586561,...,44.450830,34.133650,39.414676,37.298051,61.079395,55.442283,35.877877,44.892943,42.288697,71.451313

In [29]:
klines = client.get_historical_klines('BTCUSDT', timeInterval, startDate)
Database_Rendement = pd.DataFrame(klines,columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])
Database_Rendement = Database_Rendement.set_index(['timestamp'])
Database_Rendement.index = pd.to_datetime(Database_Rendement.index, unit='ms')
Database_Rendement = Database_Rendement.drop(columns = ['open','high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])

#Database_Rendement

Empty DataFrame
Columns: []
Index: [2017-08-17 00:00:00, 2017-08-18 00:00:00, 2017-08-19 00:00:00, 2017-08-20 00:00:00, 2017-08-21 00:00:00, 2017-08-22 00:00:00, 2017-08-23 00:00:00, 2017-08-24 00:00:00, 2017-08-25 00:00:00, 2017-08-26 00:00:00, 2017-08-27 00:00:00, 2017-08-28 00:00:00, 2017-08-29 00:00:00, 2017-08-30 00:00:00, 2017-08-31 00:00:00, 2017-09-01 00:00:00, 2017-09-02 00:00:00, 2017-09-03 00:00:00, 2017-09-04 00:00:00, 2017-09-05 00:00:00, 2017-09-06 00:00:00, 2017-09-07 00:00:00, 2017-09-08 00:00:00, 2017-09-09 00:00:00, 2017-09-10 00:00:00, 2017-09-11 00:00:00, 2017-09-12 00:00:00, 2017-09-13 00:00:00, 2017-09-14 00:00:00, 2017-09-15 00:00:00, 2017-09-16 00:00:00, 2017-09-17 00:00:00, 2017-09-18 00:00:00, 2017-09-19 00:00:00, 2017-09-20 00:00:00, 2017-09-21 00:00:00, 2017-09-22 00:00:00, 2017-09-23 00:00:00, 2017-09-24 00:00:00, 2017-09-25 00:00:00, 2017-09-26 00:00:00, 2017-09-27 00:00:00, 2017-09-28 00:00:00, 2017-09-29 00:00:00, 2017-09-30 00:00:00, 2017-10-01 00:00:00, 2017-10-02 00:00:00, 2017-10-03 00:00:00, 2017-10-04 00:00:00, 2017-10-05 00:00:00, 2017-10-06 00:00:00, 2017-10-07 00:00:00, 2017-10-08 00:00:00, 2017-10-09 00:00:00, 2017-10-10 00:00:00, 2017-10-11 00:00:00, 2017-10-12 00:00:00, 2017-10-13 00:00:00, 2017-10-14 00:00:00, 2017-10-15 00:00:00, 2017-10-16 00:00:00, 2017-10-17 00:00:00, 2017-10-18 00:00:00, 2017-10-19 00:00:00, 2017-10-20 00:00:00, 2017-10-21 00:00:00, 2017-10-22 00:00:00, 2017-10-23 00:00:00, 2017-10-24 00:00:00, 2017-10-25 00:00:00, 2017-10-26 00:00:00, 2017-10-27 00:00:00, 2017-10-28 00:00:00, 2017-10-29 00:00:00, 2017-10-30 00:00:00, 2017-10-31 00:00:00, 2017-11-01 00:00:00, 2017-11-02 00:00:00, 2017-11-03 00:00:00, 2017-11-04 00:00:00, 2017-11-05 00:00:00, 2017-11-06 00:00:00, 2017-11-07 00:00:00, 2017-11-08 00:00:00, 2017-11-09 00:00:00, 2017-11-10 00:00:00, 2017-11-11 00:00:00, 2017-11-12 00:00:00, 2017-11-13 00:00:00, 2017-11-14 00:00:00, 2017-11-15 00:00:00, 2017-11-16 00:00:00, 2017-11-17 00:00:00, 2017-11-18 00:00:00, 2017-11-19 00:00:00, 2017-11-20 00:00:00, 2017-11-21 00:00:00, 2017-11-22 00:00:00, 2017-11-23 00:00:00, 2017-11-24 00:00:00, ...]

[1894 rows x 0 columns]

In [51]:
import math
from numpy import NaN


for pair in PAIRNAME:
    klinesT = client.get_historical_klines(pair, timeInterval, startDate)
    df = pd.DataFrame(klinesT, columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])
    df['open'] = pd.to_numeric(df['open'])
    df = df.set_index(df['timestamp'])
    df.index = pd.to_datetime(df.index, unit='ms')
    Database_Rendement[f'{pair}'] = Database_Rendement.apply(lambda _: '', axis=1)
    j = 1
    for i in range(len(Database_Rendement)-len(df['open']), len(Database_Rendement)):
        Database_Rendement[f'{pair}'][i] = (((df['open'][j] - df['open'][j-1]) / df['open'][j-1])*100)      
        if j < len(df['open'])-1:    
            j+=1
        
    del df
    # print(Database_Rendement[f'{pair}'])

Database_Rendement

,test,1INCHUSDT,AAVEUSDT,ACAUSDT,ACHUSDT,ACMUSDT,ADAUSDT,ADXUSDT,AGLDUSDT,AIONUSDT,...,FLMUSDT,FLOWUSDT,FLUXUSDT,FORTHUSDT,FORUSDT,FRONTUSDT,FTMUSDT,FTTUSDT,FUNUSDT,FXSUSDT
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-08-17,,,,,,,,,,,...,,,,,,,,,,
2017-08-18,,,,,,,,,,,...,,,,,,,,,,
2017-08-19,,,,,,,,,,,...,,,,,,,,,,
2017-08-20,,,,,,,,,,,...,,,,,,,,,,
2017-08-21,,,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-19,,-0.701754,0.485437,-1.02348,-3.787879,-4.007573,-3.532009,-0.832799,-2.250804,-13.2662,...,-4.591368,-5.307995,-6.6313,-1.927711,-0.698174,-1.875273,-4.697987,-4.240882,-0.825309,-9.090909
2022-10-20,,-0.706714,-2.415459,-1.76399,-0.699913,-2.531229,-2.688787,1.937984,0.986842,-2.624937,...,-1.539942,-1.107266,-1.136364,-2.702703,-1.297999,-0.488889,0.301811,-0.708592,-0.416089,0.673235
2022-10-21,,1.245552,1.608911,-0.06192,4.845815,2.698145,2.645503,0.443599,0.977199,-1.918092,...,0.879765,1.39958,-0.718391,1.262626,-0.986301,0.223314,2.808425,0.133809,0.835655,0.815528
2022-10-22,,0.351494,0.0,2.106568,-6.806723,-1.050903,0.601375,10.851735,-0.322581,0.502114,...,1.162791,1.380262,-1.013025,0.0,13.503044,4.411765,-0.292683,0.623608,0.0,-2.993043
2022-10-23,,0.351494,0.0,2.106568,-6.806723,-1.050903,0.601375,10.851735,-0.322581,0.502114,...,1.162791,1.380262,-1.013025,0.0,13.503044,4.411765,-0.292683,0.623608,0.0,-2.993043